# Generated by Django 6.0.8 on 2026-08-23 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('used_fallback', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('blocked', 'Blocked by safety filter'), ('cancelled', 'Cancelled by client')], db_index=True, max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('request_count', models.PositiveSmallIntegerField(default=1)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('thinking_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('first_token_ms', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'chat_usage_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
