# Generated by Django 6.0.8 on 2026-08-23 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['user', '-created_at'], name='usage_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['model', '-created_at'], name='usage_model_created_idx'),
        ),
    ]
